# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-31 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_usergeokey_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergeokey',
            name='geokey',
            field=models.CharField(max_length=500),
        ),
    ]
