# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-10 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180131_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergeokey',
            name='is_map',
        ),
    ]
